version: "3"
services:
  edgedb:
    container_name: edgedb
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
      - ".edgedb.toml:/edgedb.toml"
    ports:
      - "5656:5656"
