# AUTOGENERATED FROM 'get_people.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetPeopleResult(NoPydanticValidation):
    name: str
    id: uuid.UUID


async def get_people(
    executor: edgedb.AsyncIOExecutor,
) -> list[GetPeopleResult]:
    return await executor.query(
        """\
        select Person { name, id };\
        """,
    )
